# 项目相关配置
fast:
  # 名称
  name: SYSTEM-PLATFORM
  # 版本
  version: 1.0.1
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/fast/uploadPath，Linux配置 /home/fast/uploadPath）
  profile: D:/fast/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8886
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.platform: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  1024MB
      # 设置总上传的文件大小
      max-request-size:  2048MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 100s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.platform.project.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml,classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.platform.project.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml,classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

wx:
  appid: wx386922d6cba7e422
  secret: ed7bec3f07bfe3294ee447fa5cc063e3
  token: lkhBSJvfypxEfuX7
  aesKey: OGBphwCI0e1DbVj30kCXashpGNra6RM596YQcfDOW1x
  msgDataFormat: JSON

cos:
  baseUrl: clf-1314105014.cos.ap-shanghai.myqcloud.com
  accessKey: AKIDOODxRgiYBmBOPCm8PSwEWbS6dy74pOtK
  secretKey: HNSPFvUxUs21mPo6bx5zgCVecOzNagfW
  regionName: ap-shanghai
  bucketName: clf-1314105014
  folderPrefix: /files

qiniu:
  accessKey: G6iHWX1bXvsohFPRirdnbnYjZwSwyfAb_joDIbAe
  secretKey: eFmlS8ou5GsHOV7_BfR6XkjYPwpt-etxWtl9Ve3b
  bucket: clf2022
  prefix: colorfulvision.cn

# 代码生成
gen:
  # 作者
  author: fast
  # 前端生成文件目录
  webFilePath: F:/2022GO/fast-ui/src
  # 后端生成文件目录
  serverFilePath: F:/2022GO/fast-platform/src
  # sql文件目录
  sqlFilePath: F:/2022GO/fast-platform/src/main/resources/sql
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.platform.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: module_

matlab:
  exe:
    path: E:\IDE\matlab2022a\bin\matlab.exe
  file:
    path: H:\Desktop\matlabRock